In [2]:
import os
from dateutil.parser import parse as dateutil_parse
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

PATH = 'season_1/'
CLEAN_PATH = PATH+'clean/'

%matplotlib inline

In [3]:
gaps1 = pd.read_csv(CLEAN_PATH+'train_gap.csv',index_col=0)
gaps2 = pd.read_csv(CLEAN_PATH+'test_gap.csv',index_col=0)

# find the most matched day from triaining data, use its gap as answer

In [50]:
best_choice = np.zeros((5,2))
best_choice[0]

array([ 0.,  0.])

In [53]:
for i in range(len(gaps2.columns)):
    for j in range(len(gaps1.columns)):
        j_theta = 0
        for k in range(len(gaps2)):
            if(gaps2.ix(k, i) != 0):
                s = gaps1.ix[k, j] - gaps2.ix[k, i]
                j_theta += s*s
        if(j_theta < best_choice[i][1] or best_choice[i][1] == 0):
            best_choice[i][0] = j
            best_choice[i][1] = j_theta

In [54]:
best_choice

array([[  1.00000000e+00,   3.70336910e+07],
       [  2.00000000e+00,   1.21224920e+07],
       [  1.00000000e+00,   3.25709890e+07],
       [  1.00000000e+00,   2.76303710e+07],
       [  1.00000000e+00,   1.63904090e+07]])

In [101]:
asked_gap = pd.read_table(PATH + 'test_set_1/read_me_1.txt', header=None)

In [102]:
asked_gap['answer'] = np.zeros((len(asked_gap)))

In [103]:
asked_gap.columns = ['year','month','day','piece','answer']

In [111]:
asked_gap

    year  month  day  piece  answer
0   2016      1   22     46     0.0
1   2016      1   22     58     0.0
2   2016      1   22     70     0.0
3   2016      1   22     82     0.0
4   2016      1   22     94     0.0
5   2016      1   22    106     0.0
6   2016      1   22    118     0.0
7   2016      1   22    130     0.0
8   2016      1   22    142     0.0
9   2016      1   24     58     0.0
10  2016      1   24     70     0.0
11  2016      1   24     82     0.0
12  2016      1   24     94     0.0
13  2016      1   24    106     0.0
14  2016      1   24    118     0.0
15  2016      1   24    130     0.0
16  2016      1   24    142     0.0
17  2016      1   26     46     0.0
18  2016      1   26     58     0.0
19  2016      1   26     70     0.0
20  2016      1   26     82     0.0
21  2016      1   26     94     0.0
22  2016      1   26    106     0.0
23  2016      1   26    118     0.0
24  2016      1   26    130     0.0
25  2016      1   26    142     0.0
26  2016      1   28     58     0.0
27  2016      1   28     70     0.0
28  2016      1   28     82     0.0
29  2016      1   28     94     0.0
30  2016      1   28    106     0.0
31  2016      1   28    118     0.0
32  2016      1   28    130     0.0
33  2016      1   28    142     0.0
34  2016      1   30     46     0.0
35  2016      1   30     58     0.0
36  2016      1   30     70     0.0
37  2016      1   30     82     0.0
38  2016      1   30     94     0.0
39  2016      1   30    106     0.0
40  2016      1   30    118     0.0
41  2016      1   30    130     0.0
42  2016      1   30    142     0.0

In [112]:
asked_gap.loc[0, 'piece']

46.0

# generate answer

In [130]:
for i in range(len(asked_gap)):
    asked_gap.loc[i, 'answer'] = gaps1.ix[asked_gap.ix[i, 'piece'], int(best_choice[(asked_gap.ix[i, 'day'] - 22) / 2][0])]
    if(asked_gap.loc[i, 'answer'] < 300):
        asked_gap.loc[i, 'answer'] = 0

In [131]:
asked_gap

    year  month  day  piece  answer
0   2016      1   22     46     0.0
1   2016      1   22     58   414.0
2   2016      1   22     70   331.0
3   2016      1   22     82   684.0
4   2016      1   22     94     0.0
5   2016      1   22    106   379.0
6   2016      1   22    118     0.0
7   2016      1   22    130     0.0
8   2016      1   22    142   351.0
9   2016      1   24     58     0.0
10  2016      1   24     70   441.0
11  2016      1   24     82   414.0
12  2016      1   24     94     0.0
13  2016      1   24    106     0.0
14  2016      1   24    118   682.0
15  2016      1   24    130   765.0
16  2016      1   24    142   302.0
17  2016      1   26     46     0.0
18  2016      1   26     58   414.0
19  2016      1   26     70   331.0
20  2016      1   26     82   684.0
21  2016      1   26     94     0.0
22  2016      1   26    106   379.0
23  2016      1   26    118     0.0
24  2016      1   26    130     0.0
25  2016      1   26    142   351.0
26  2016      1   28     58   414.0
27  2016      1   28     70   331.0
28  2016      1   28     82   684.0
29  2016      1   28     94     0.0
30  2016      1   28    106   379.0
31  2016      1   28    118     0.0
32  2016      1   28    130     0.0
33  2016      1   28    142   351.0
34  2016      1   30     46     0.0
35  2016      1   30     58   414.0
36  2016      1   30     70   331.0
37  2016      1   30     82   684.0
38  2016      1   30     94     0.0
39  2016      1   30    106   379.0
40  2016      1   30    118     0.0
41  2016      1   30    130     0.0
42  2016      1   30    142   351.0

In [132]:
asked_gap.to_csv(PATH+'clean/asked_gap.csv')